### PR TITLE
feat:created navigation for desktop

### PR DESCRIPTION
**Pull request by KamiyaGaikwad**

### CODE REVIEW

**Comment by shrey27** [comment]
There is issue with responsiveness. Check the ss taken in mobile view.
issue
.

**Comment by KamiyaGaikwad** [comment]
@shrey27 thank you for pointing it out, I will correct it

**Review by shrey27 — APPROVED** [review]
good to merge

**Review by vinc3nati — APPROVED** [review]
Looks clean!

**Pull request merged**
