### PR TITLE
Alert,button

### PR DESCRIPTION
**Pull request by KamiyaGaikwad**

### CODE REVIEW

**Review by rohit8686 — APPROVED** [review]
Looks good ! but try using var for colors

**Comment by KamiyaGaikwad** [comment]
@rohit8686 thank you for your suggestion. I will make the changes.

**Review by thegeorgenikhil — APPROVED** [review]
Same as Rohan 
-refactor the colors using CSS variables

Everything else looks good.
Approving this, hope you do the changes before merging👍.

**Comment by KamiyaGaikwad** [comment]
Thank you for the suggestion @thegeorgenikhil. I have done the changes

**Pull request merged**
